# Generated by Django 5.2.5 on 2025-08-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('unisex', 'Unisex')], max_length=200)),
                ('category', models.CharField(choices=[('Analog', 'Analog'), ('Digital', 'Digital'), ('Smartwatch', 'Smartwatch'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
